[tool.poetry]
name = "jupiter-notes"
version = "0.1.0"
description = ""
authors = ["F4ever <raman.s@lido.fi>"]
license = "MIT"
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = "^3.12"
jupyterlab = "^4.3.4"
jupyterlab-execute-time = "^3.2.0"
jupyterlab-skip-traceback = "^5.1.0"
jupyterlab-lsp = "^5.1.0"
python-lsp-server = "^1.12.0"
jupyterlab-unfold = "^0.3.3"
theme-darcula = "^4.0.0"
pyright = "^1.1.392.post0"
ipywidgets = "^8.1.5"
numpy = "^2.2.2"
matplotlib = "^3.10.0"
web3 = "^7.7.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
